# Generated by Django 5.0.1 on 2024-02-18 10:14

import videoData.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoSource', models.CharField(default='Where did you get the video', max_length=100)),
                ('videoFile', models.FileField(upload_to='video/%y', validators=[videoData.validators.file_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
