# Generated by Django 5.0.1 on 2024-02-18 10:33

import videoData.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='videoFile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[videoData.validators.file_size]),
        ),
    ]
