# Generated by Django 5.0.1 on 2024-02-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
    ]
